version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    ports:
      - 5433:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
  backend:
    image: 'danny247/don-remolo-backend'
    tty: true
    ports:
      - '44390:80'
    environment:
      - ConnectionStrings__DefaultConnection=Server=db; User Id=appuser; Password=secret; Database=DonRemolo
      - ASPNETCORE_ENVIRONMENT=Development
      - Token__Key=My super secret key
      - Token__Issuer=http://localhost:44390
      - ApiUrl=http://localhost:44390/
      - FacebookAuthSettings__AppId=1273805316692082
      - FacebookAuthSettings__AppSecret=0b410dab073c27b604a24baae0e117a0
      - GoogleAuthSettings__ClientId=876166062131-v0bj8o9ka4c777q6bkrmcevqh9q3fiut.apps.googleusercontent.com
    depends_on:
      - db
  # frontend:
  # image: "danny247/fashion-like-frontend"
  # tty: true
  # ports:
  # - '80:3000'
  # depends_on:
  # - backend
#docker-compose up
