import Head from 'next/head';
import { useState } from 'react';
import Modal from '../modules/shared/Modal';
import { Main as Login } from '../modules/login/Main';
import { Main as Register } from '../modules/register/Main';

export default function Home() {
	const [isLogin, setIsLogin] = useState(false);
	const [isRegister, setIsRegister] = useState(false);

	const handleModal = (e) => {
		e.target.dataset.modal === 'login'
			? setIsLogin(!isLogin)
			: e.target.dataset.modal === 'register'
			? setIsRegister(!isRegister)
			: null;
	};

	return (
		<div>
			<Head>
				<title>Pizzeria Don Rémolo</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			{isLogin && (
				<Modal
					handleModal={handleModal}
					isModal={isLogin}
					setIsModal={setIsLogin}
					modal="login"
				>
					<Login handleModal={handleModal} />
				</Modal>
			)}
			{isRegister && (
				<Modal
					handleModal={handleModal}
					isModal={isRegister}
					setIsModal={setIsRegister}
					modal="register"
				>
					<Register handleModal={handleModal} />
				</Modal>
			)}
		</div>
	);
};